
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
titanic_df = pd.read_csv("CodSoft\Task1\Titanic-Dataset.csv")
print("First 10 rows of the dataset:")
print(titanic_df.head(10))
print("\nLast 10 rows of the dataset:")
print(titanic_df.tail(10))
print("\nDataset Information:")
print(titanic_df.info())
print("\nSummary Statistics:")
print(titanic_df.describe())
print("\nNumber of missing values for each column:")
print(titanic_df.isnull().sum())
print("\nUnique values for each categorical column:")
print(titanic_df[['Sex', 'Embarked']].nunique())
titanic_df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1, inplace=True)
print("\nFirst 10 rows after dropping unnecessary columns:")
print(titanic_df.head(10))
titanic_df.fillna({'Age': titanic_df['Age'].median()}, inplace=True)
titanic_df.fillna({'Embarked': titanic_df['Embarked'].mode()[0]}, inplace=True)
print("\nNumber of missing values after filling:")
print(titanic_df.isnull().sum())
le = LabelEncoder()
titanic_df['Sex'] = le.fit_transform(titanic_df['Sex'])
titanic_df['Embarked'] = le.fit_transform(titanic_df['Embarked'])
print("\nFirst 10 rows after encoding categorical variables:")
print(titanic_df.head(10))
print("\nCorrelation Matrix:")
print(titanic_df.corr())
plt.figure(figsize=(12, 10))
sns.heatmap(titanic_df.corr(), annot=True, cmap='coolwarm', linewidths=0.5)
plt.title('Correlation Matrix')
plt.show()
X = titanic_df.drop('Survived', axis=1)
y = titanic_df['Survived']
print("\nFeatures:")
print(X.head())
print("\nTarget Variable:")
print(y.head())
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("\nShapes of training and testing sets:")
print(f"X_train: {X_train.shape}")
print(f"X_test: {X_test.shape}")
print(f"y_train: {y_train.shape}")
print(f"y_test: {y_test.shape}")
print("\nDistribution of target variable in training set:")
print(y_train.value_counts(normalize=True))
print("\nDistribution of target variable in testing set:")
print(y_test.value_counts(normalize=True))
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'\nAccuracy: {accuracy:.2f}')
print('\nClassification Report:')
print(classification_report(y_test, y_pred))
print('\nConfusion Matrix:')
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)
plt.figure(figsize=(10, 7))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()
feature_importances = rf.feature_importances_
features = X.columns
feature_importance_df = pd.DataFrame({'Feature': features, 'Importance': feature_importances})
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)
print("\nFeature Importances:")
print(feature_importance_df)
plt.figure(figsize=(10, 7))
sns.barplot(x='Importance', y='Feature', data=feature_importance_df)
plt.title('Feature Importances')
plt.show()
print("\nDetailed Evaluation Metrics:")
true_positive = conf_matrix[1, 1]
true_negative = conf_matrix[0, 0]
false_positive = conf_matrix[0, 1]
false_negative = conf_matrix[1, 0]
print(f"True Positive: {true_positive}")
print(f"True Negative: {true_negative}")
print(f"False Positive: {false_positive}")
print(f"False Negative: {false_negative}")
precision = true_positive / (true_positive + false_positive)
recall = true_positive / (true_positive + false_negative)
f1_score = 2 * (precision * recall) / (precision + recall)
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1_score:.2f}")
plt.figure(figsize=(10, 7))
sns.histplot(titanic_df['Age'], bins=30, kde=True)
plt.title('Distribution of Age')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()
plt.figure(figsize=(10, 7))
sns.barplot(x='Sex', y='Survived', data=titanic_df)
plt.title('Survival Rate by Sex')
plt.xlabel('Sex')
plt.ylabel('Survival Rate')
plt.show()
plt.figure(figsize=(10, 7))
sns.barplot(x='Pclass', y='Survived', data=titanic_df)
plt.title('Survival Rate by Class')
plt.xlabel('Class')
plt.ylabel('Survival Rate')
plt.show()
plt.figure(figsize=(10, 7))
sns.barplot(x='Embarked', y='Survived', data=titanic_df)
plt.title('Survival Rate by Embarked')
plt.xlabel('Embarked')
plt.ylabel('Survival Rate')
plt.show()
